import React from 'react';
import { ArrowNarrowRightIcon, CheckCircleIcon } from '@heroicons/react/solid';
import { useNavigate, useParams } from 'react-router-dom';


const ServiceDetails = () => {
    const { serviceID } = useParams({});
    const navigate = useNavigate();

    return (
        <section className='w-10/12 mx-auto border-2 rounded-md mt-10 lg:px-24'>
            <div className="image h-[300px] mt-0 lg:mt-8">
                <img className='w-full h-full mx-auto border-2 rounded-2xl' src="https://i.ibb.co/2S7p0NG/10020.png" alt="details" />
            </div>
            <h1 className='text-[#1F2937] text-2xl font-bold capitalize text-left p-4'>A Good Traveler Has No Fixed Plans And Is Not Intent On Arriving <span className='text-yellow-600 capitalize font-bold text-2xl'>Your product id iS</span> = <span className='text-red-600'>{serviceID}</span>. </h1>
            <p className='text-md text-left p-3 text-gray-600 text-sm sm:text-md font-light sm:font-normal'>Malaysia was once ranked 9th in the world for tourist arrivals.[1] The Travel and Tourism Competitiveness Report 2017 ranks Malaysia 25th out of 141 countries overall.

                In an effort to diversify the economy and make Malaysia's economy less dependent on exports, the government pushed to increase tourism in Malaysia. As a result, tourism has become Malaysia's third largest source of foreign exchange income,[2] and accounted for 7% of Malaysia's economy as of 2005.[3]

                The government agency in charge of promoting tourism in Malaysia is Tourism Malaysia or the Malaysia Tourism Promotion Board (MTPB). On 20 May 1987, the Ministry of Culture, Arts and Tourism (MOCAT) was established and TDC moved to this new ministry. TDC existed from 1972 to 1992, when it became the Malaysia Tourism Promotion Board (MTPB), through the Malaysia Tourism Promotion Board Act, 1992.

                In 1999, Malaysia launched a worldwide marketing campaign called "Malaysia, Truly Asia" which was largely successful and brought in over 7.4 million tourists.[4] The extra revenue generated by tourism helped the country's economy during the economic crisis of 2008.[5]</p>
            <div className='flex justify-evenly'>
                <div className='advantage  border-2 rounded-2xl lg:py-6 lg:px-10 w-5/12 '>
                    <h1 className=' text-center text-[#1F2937] text-lg my-3 lg:text-2xl font-bold capitalize'>advantage</h1>
                    <ul className='py-2 text-left'><li><span className='ml-2 text-gray-600 text-sm sm:text-md font-light sm:font-normal capitalize'><CheckCircleIcon className='w-4 h-4 lg:w-6 lg:h-6 inline text-green-600' />Cruise dinner </span></li></ul>
                    <ul className='py-2 text-left'><li><span className='ml-2 text-gray-600 text-sm sm:text-md font-light sm:font-normal capitalize'><CheckCircleIcon className='w-4 h-4 lg:w-6 lg:h-6 inline text-green-600' />3 Meal per day</span></li></ul>
                    <ul className='py-2 text-left'><li><span className='ml-2 text-gray-600 text-sm sm:text-md font-light sm:font-normal capitalize'><CheckCircleIcon className='w-4 h-4 lg:w-6 lg:h-6 inline text-green-600' />Pick and drop services</span></li></ul>
                    <ul className='py-2 text-left'><li><span className='ml-2 text-gray-600 text-sm sm:text-md font-light sm:font-normal capitalize'><CheckCircleIcon className='w-4 h-4 lg:w-6 lg:h-6 inline text-green-600' />Smoking allow</span></li></ul>
                    <ul className='py-2 text-left'><li><span className='ml-2 text-gray-600 text-sm sm:text-md font-light sm:font-normal capitalize'><CheckCircleIcon className='w-4 h-4 lg:w-6 lg:h-6 inline text-green-600' />Valet parking</span></li></ul>
                    <ul className='py-2 text-left'><li><span className='ml-2 text-gray-600 text-sm sm:text-md font-light sm:font-normal capitalize'><CheckCircleIcon className='w-4 h-4 lg:w-6 lg:h-6 inline text-green-600' />music event</span></li></ul>

                    <div className='text-center'>
                        <h6 className='mx-auto font-bold capitalize border rounded-full mb-5 text-sm md:text-lg inline-block md:px-5 px-3 py-3 md:py-3 mt-5 bg-[#1F2937] text-white'>price: $500</h6>
                    </div>
                </div>
                <div className='advantage border-2 rounded-2xl lg:py-6 lg:px-10 w-5/12 '>
                    <h1 className=' text-center text-[#1F2937] text-lg my-3 lg:text-2xl font-bold capitalize'>advantage</h1>
                    <ul className='py-2 text-left'><li><span className='ml-2 text-gray-600 text-sm sm:text-md font-light sm:font-normal capitalize'><CheckCircleIcon className='w-4 h-4 lg:w-6 lg:h-6 inline text-green-600' />Cruise dinner </span></li></ul>
                    <ul className='py-2 text-left'><li><span className='ml-2 text-gray-600 text-sm sm:text-md font-light sm:font-normal capitalize'><CheckCircleIcon className='w-4 h-4 lg:w-6 lg:h-6 inline text-green-600' />3 Meal per day</span></li></ul>
                    <ul className='py-2 text-left'><li><span className='ml-2 text-gray-600 text-sm sm:text-md font-light sm:font-normal capitalize'><CheckCircleIcon className='w-4 h-4 lg:w-6 lg:h-6 inline text-green-600' />Pick and drop services</span></li></ul>
                    <ul className='py-2 text-left'><li><span className='ml-2 text-gray-600 text-sm sm:text-md font-light sm:font-normal capitalize'><CheckCircleIcon className='w-4 h-4 lg:w-6 lg:h-6 inline text-green-600' />Smoking allow</span></li></ul>
                    <ul className='py-2 text-left'><li><span className='ml-2 text-gray-600 text-sm sm:text-md font-light sm:font-normal capitalize'><CheckCircleIcon className='w-4 h-4 lg:w-6 lg:h-6 inline text-green-600' />Valet parking</span></li></ul>
                    <ul className='py-2 text-left'><li><span className='ml-2 text-gray-600 text-sm sm:text-md font-light sm:font-normal capitalize'><CheckCircleIcon className='w-4 h-4 lg:w-6 lg:h-6 inline text-green-600' />music event</span></li></ul>

                    <div className='text-center'>
                        <h6 className='mx-auto font-bold capitalize border rounded-full mb-5 text-sm md:text-lg inline-block md:px-5 px-3 py-3 md:py-3 mt-5 bg-[#1F2937] text-white'>price: $500</h6>
                    </div>
                </div>
            </div>
            <div className='flex justify-between px-4'>
                <div></div>
                <div onClick={() => navigate('/checkout')}>
                    <button className='text-center mt-10 border rounded-md px-4 py-2 mb-4 border-[#cca001] hover:bg-[#cca001]'>Procede to CheckOut <ArrowNarrowRightIcon className='text-sm  w-6 h-6  inline'></ArrowNarrowRightIcon></button>
                </div>
            </div>


        </section>
    );
};

export default ServiceDetails;